#include "../interface/GeneralTree.h"

#define NJET 20
#define NSUBJET 2

GeneralTree::GeneralTree() {
//STARTCUSTOMCONST
  for (unsigned iS=0; iS!=6; ++iS) {
    scale[iS] = 1;
  }
  
  for (auto ibeta : ibetas) {
    for (auto N : Ns) {
      for (auto order : orders) {
        ECFParams p;
        p.ibeta = ibeta;
        p.N = N;
        p.order = order;
        ecfParams.push_back(p);
        fj1ECFNs[p] = -1;
      }
    }
  }

  for (unsigned iShift=0; iShift!=bNShift; ++iShift) {
    for (unsigned iJet=0; iJet!=bNJet; ++iJet) {
      for (unsigned iTags=0; iTags!=bNTags; ++iTags) {
        BTagParams p;
        p.jet = (BTagJet)iJet;
        p.tag = (BTagTags)iTags;
        p.shift = (BTagShift)iShift;
        btagParams.push_back(p);
        sf_btags[p] = 1;
      }
    }
  }

  for (unsigned int iSJ=0; iSJ!=NSUBJET; ++iSJ) {
    fj1sjPt[iSJ] = -1;
    fj1sjEta[iSJ] = -1;
    fj1sjPhi[iSJ] = -1;
    fj1sjM[iSJ] = -1;
    fj1sjCSV[iSJ] = -1;
    fj1sjQGL[iSJ] = -1;
  }
  for (unsigned int iJ=0; iJ!=NJET; ++iJ) {
    jetPt[iJ] = -1;
    jetEta[iJ] = -1;
    jetPhi[iJ] = -1;
    jetE[iJ] = -1;
    jetCSV[iJ] = -1;
    jetIso[iJ] = -1;
    jetQGL[iJ] = -1;
    jetLeadingLepPt[iJ] = -1;
    jetLeadingTrkPt[iJ] = -1;
    jetNLep[iJ] = -1;
    jetEMFrac[iJ] = -1;
    jetHadFrac[iJ] = -1;
    jetGenFlavor[iJ] = -1;
  }

//ENDCUSTOMCONST
}

GeneralTree::~GeneralTree() {
//STARTCUSTOMDEST
//ENDCUSTOMDEST
}

void GeneralTree::Reset() {
//STARTCUSTOMRESET
  for (unsigned iS=0; iS!=6; ++iS) {
    scale[iS] = 1;
  }

  for (auto p : ecfParams) { 
    fj1ECFNs[p] = -1;
  }

  for (auto p : btagParams) { 
    sf_btags[p] = 1;
  }

  for (unsigned int iSJ=0; iSJ!=NSUBJET; ++iSJ) {
    fj1sjPt[iSJ] = -99;
    fj1sjEta[iSJ] = -99;
    fj1sjPhi[iSJ] = -99;
    fj1sjM[iSJ] = -99;
    fj1sjCSV[iSJ] = -99;
    fj1sjQGL[iSJ] = -99;
  }
  for (unsigned int iJ=0; iJ!=NJET; ++iJ) {
    jetPt[iJ] = -99;
    jetEta[iJ] = -99;
    jetPhi[iJ] = -99;
    jetE[iJ] = -99;
    jetCSV[iJ] = -99;
    jetIso[iJ] = -99;
    jetQGL[iJ] = -99;
    jetLeadingLepPt[iJ] = -99;
    jetLeadingTrkPt[iJ] = -99;
    jetEMFrac[iJ] = -1;
    jetHadFrac[iJ] = -1;
    jetNLep[iJ] = -99;
    jetGenPt[iJ] = -99;
    jetGenFlavor[iJ] = -99;
  }

  for (auto iter=signal_weights.begin(); iter!=signal_weights.end(); ++iter) {
    signal_weights[iter->first] = 1; // does pair::second return a reference?
  }

//ENDCUSTOMRESET
    looseLep1D0 = -1;
    looseLep1Dz = -1;
    looseLep2D0 = -1;
    looseLep2Dz = -1;
    looseLep3D0 = -1;
    looseLep3Dz = -1;
    looseLep4D0 = -1;
    looseLep4Dz = -1;
    looseLep1ChIsoPh = -1;
    looseLep1NhIsoPh = -1;
    looseLep1PhIsoPh = -1;
    looseLep1EcalIso = -1;
    looseLep1HcalIso = -1;
    looseLep1TrackIso = -1;
    looseLep1IsoPUOffset = -1;
    looseLep1Sieie = -1;
    looseLep1Sipip = -1;
    looseLep1DEtaInSeed = -1;
    looseLep1DPhiIn = -1;
    looseLep1Eseed = -1;
    looseLep1HOverE = -1;
    looseLep1EcalE = -1;
    looseLep1TrackP = -1;
    looseLep1NMissingHits = 0;
    looseLep1TripleCharge = 0;
    looseLep2ChIsoPh = -1;
    looseLep2NhIsoPh = -1;
    looseLep2PhIsoPh = -1;
    looseLep2EcalIso = -1;
    looseLep2HcalIso = -1;
    looseLep2TrackIso = -1;
    looseLep2IsoPUOffset = -1;
    looseLep2Sieie = -1;
    looseLep2Sipip = -1;
    looseLep2DEtaInSeed = -1;
    looseLep2DPhiIn = -1;
    looseLep2Eseed = -1;
    looseLep2HOverE = -1;
    looseLep2EcalE = -1;
    looseLep2TrackP = -1;
    looseLep2NMissingHits = 0;
    looseLep2TripleCharge = 0;
    looseLep3ChIsoPh = -1;
    looseLep3NhIsoPh = -1;
    looseLep3PhIsoPh = -1;
    looseLep3EcalIso = -1;
    looseLep3HcalIso = -1;
    looseLep3TrackIso = -1;
    looseLep3IsoPUOffset = -1;
    looseLep3Sieie = -1;
    looseLep3Sipip = -1;
    looseLep3DEtaInSeed = -1;
    looseLep3DPhiIn = -1;
    looseLep3Eseed = -1;
    looseLep3HOverE = -1;
    looseLep3EcalE = -1;
    looseLep3TrackP = -1;
    looseLep3NMissingHits = 0;
    looseLep3TripleCharge = 0;
    looseLep4ChIsoPh = -1;
    looseLep4NhIsoPh = -1;
    looseLep4PhIsoPh = -1;
    looseLep4EcalIso = -1;
    looseLep4HcalIso = -1;
    looseLep4TrackIso = -1;
    looseLep4IsoPUOffset = -1;
    looseLep4Sieie = -1;
    looseLep4Sipip = -1;
    looseLep4DEtaInSeed = -1;
    looseLep4DPhiIn = -1;
    looseLep4Eseed = -1;
    looseLep4HOverE = -1;
    looseLep4EcalE = -1;
    looseLep4TrackP = -1;
    looseLep4NMissingHits = 0;
    looseLep4TripleCharge = 0;
    looseLep1SelBit = 0;
    looseLep2SelBit = 0;
    looseLep3SelBit = 0;
    looseLep4SelBit = 0;
    looseLep3PdgId = 0;
    looseLep3IsTight = 0;
    looseLep3IsHLTSafe = 0;
    looseLep3Pt = -1;
    looseLep3Eta = -1;
    looseLep3Phi = -1;
    looseLep4PdgId = 0;
    looseLep4Pt = -1;
    looseLep4Eta = -1;
    looseLep4Phi = -1;
    looseLep4IsTight = 0;
    looseLep4IsHLTSafe = 0;
    sf_trk1 = 1;
    sf_loose1 = 1;
    sf_medium1 = 1;
    sf_tight1 = 1;
    sf_unc1 = 1;
    sf_trk2 = 1;
    sf_loose2 = 1;
    sf_medium2 = 1;
    sf_tight2 = 1;
    sf_unc2 = 1;
    sf_trk3 = 1;
    sf_loose3 = 1;
    sf_medium3 = 1;
    sf_tight3 = 1;
    sf_unc3 = 1;
    sf_trk4 = 1;
    sf_loose4 = 1;
    sf_medium4 = 1;
    sf_tight4 = 1;
    sf_unc4 = 1;
    looseLep1IsSoftMuon = 0;
    looseLep1IsGlobalMuon = 0;
    looseLep1IsTrackerMuon = 0;
    looseLep1NValidMuon = 0;
    looseLep1NValidPixel = 0;
    looseLep1TrkLayersWithMmt = 0;
    looseLep1PixLayersWithMmt = 0;
    looseLep1NMatched = 0;
    looseLep1Chi2LocalPosition = 0;
    looseLep1TrkKink = 0;
    looseLep1ValidFraction = 0;
    looseLep1NormChi2 = -1;
    looseLep1SegmentCompatibility = -1;
    looseLep2IsSoftMuon = 0;
    looseLep2IsGlobalMuon = 0;
    looseLep2IsTrackerMuon = 0;
    looseLep2NValidMuon = 0;
    looseLep2NValidPixel = 0;
    looseLep2TrkLayersWithMmt = 0;
    looseLep2PixLayersWithMmt = 0;
    looseLep2NMatched = 0;
    looseLep2Chi2LocalPosition = 0;
    looseLep2TrkKink = 0;
    looseLep2ValidFraction = 0;
    looseLep2NormChi2 = -1;
    looseLep2SegmentCompatibility = -1;
    looseLep3IsSoftMuon = 0;
    looseLep3IsGlobalMuon = 0;
    looseLep3IsTrackerMuon = 0;
    looseLep3NValidMuon = 0;
    looseLep3NValidPixel = 0;
    looseLep3TrkLayersWithMmt = 0;
    looseLep3PixLayersWithMmt = 0;
    looseLep3NMatched = 0;
    looseLep3Chi2LocalPosition = 0;
    looseLep3TrkKink = 0;
    looseLep3ValidFraction = 0;
    looseLep3NormChi2 = -1;
    looseLep3SegmentCompatibility = -1;
    looseLep4IsSoftMuon = 0;
    looseLep4IsGlobalMuon = 0;
    looseLep4IsTrackerMuon = 0;
    looseLep4NValidMuon = 0;
    looseLep4NValidPixel = 0;
    looseLep4TrkLayersWithMmt = 0;
    looseLep4PixLayersWithMmt = 0;
    looseLep4NMatched = 0;
    looseLep4Chi2LocalPosition = 0;
    looseLep4TrkKink = 0;
    looseLep4ValidFraction = 0;
    looseLep4NormChi2 = -1;
    looseLep4SegmentCompatibility = -1;
    whichRecoil = 0;
    genJet1Pt = -1;
    genJet2Pt = -1;
    genJet1Eta = -1;
    genJet2Eta = -1;
    genMjj = -1;
    sf_qcdV_VBF2lTight = 1;
    sf_qcdV_VBF2l = 1;
    barrelHTMiss = -1;
    barrelJet12Pt = -1;
    barrelJet1Pt = -1;
    barrelJet1Eta = -1;
    barrelHT = -1;
    sf_puUp = 1;
    sf_puDown = 1;
    genMuonPt = -1;
    genMuonEta = -1;
    genElectronPt = -1;
    genElectronEta = -1;
    genTauPt = -1;
    genTauEta = -1;
    badECALFilter = 0;
    sf_qcdV_VBFTight = 1;
    sf_metTrigVBF = 1;
    sf_metTrigZmmVBF = 1;
    sumETRaw = -1;
    jot1VBFID = 0;
    sf_metTrigZmm = 1;
    sf_qcdV_VBF = 1;
    jetNMBtags = 0;
    pfmetRaw = -1;
    nAK8jet = 0;
    ak81Pt = -1;
    ak81Eta = -1;
    ak81Phi = -1;
    ak81MaxCSV = -1;
    nB = 0;
    fj1MSDScaleUp_sj = -1;
    fj1MSDScaleDown_sj = -1;
    fj1MSDSmeared_sj = -1;
    fj1MSDSmearedUp_sj = -1;
    fj1MSDSmearedDown_sj = -1;
    fj1PtScaleUp_sj = -1;
    fj1PtScaleDown_sj = -1;
    fj1PtSmeared_sj = -1;
    fj1PtSmearedUp_sj = -1;
    fj1PtSmearedDown_sj = -1;
    jot2EtaUp = -1;
    jot2EtaDown = -1;
    jot1EtaUp = -1;
    jot1EtaDown = -1;
    jot1PtUp = -1;
    jot1PtDown = -1;
    jot2PtUp = -1;
    jot2PtDown = -1;
    jot12MassUp = -1;
    jot12DEtaUp = -1;
    jot12DPhiUp = -1;
    jot12MassDown = -1;
    jot12DEtaDown = -1;
    jot12DPhiDown = -1;
    pfmetUp = -1;
    pfmetDown = -1;
    pfUWmagUp = -1;
    pfUZmagUp = -1;
    pfUAmagUp = -1;
    pfUmagUp = -1;
    pfUWmagDown = -1;
    pfUZmagDown = -1;
    pfUAmagDown = -1;
    pfUmagDown = -1;
    nJot = 0;
    jot1Phi = -1;
    jot1Pt = -1;
    jot1GenPt = -1;
    jot1Eta = -1;
    jot2Phi = -1;
    jot2Pt = -1;
    jot2GenPt = -1;
    jot2Eta = -1;
    jot12DPhi = -1;
    isGS = 0;
    fj1SubMaxCSV = -1;
    looseLep1IsHLTSafe = 0;
    looseLep2IsHLTSafe = 0;
    runNumber = 0;
    lumiNumber = 0;
    eventNumber = 0;
    npv = 0;
    pu = 0;
    mcWeight = -1;
    trigger = 0;
    metFilter = 0;
    egmFilter = 0;
    filter_maxRecoil = -1;
    filter_whichRecoil = -1;
    sf_ewkV = 1;
    sf_qcdV = 1;
    sf_ewkV2j = 1;
    sf_qcdV2j = 1;
    sf_qcdTT = 1;
    sf_lepID = 1;
    sf_lepIso = 1;
    sf_lepTrack = 1;
    sf_pho = 1;
    sf_eleTrig = 1;
    sf_phoTrig = 1;
    sf_metTrig = 1;
    sf_pu = 1;
    sf_npv = 1;
    sf_tt = 1;
    sf_tt_ext = 1;
    sf_tt_bound = 1;
    sf_tt8TeV = 1;
    sf_tt8TeV_ext = 1;
    sf_tt8TeV_bound = 1;
    sf_phoPurity = 1;
    pfmet = -1;
    pfmetphi = -1;
    pfmetnomu = -1;
    puppimet = -1;
    puppimetphi = -1;
    calomet = -1;
    calometphi = -1;
    pfcalobalance = -1;
    sumET = -1;
    trkmet = -1;
    puppiUWmag = -1;
    puppiUWphi = -1;
    puppiUZmag = -1;
    puppiUZphi = -1;
    puppiUAmag = -1;
    puppiUAphi = -1;
    puppiUperp = -1;
    puppiUpara = -1;
    puppiUmag = -1;
    puppiUphi = -1;
    pfUWmag = -1;
    pfUWphi = -1;
    pfUZmag = -1;
    pfUZphi = -1;
    pfUAmag = -1;
    pfUAphi = -1;
    pfUperp = -1;
    pfUpara = -1;
    pfUmag = -1;
    pfUphi = -1;
    dphipfmet = -1;
    dphipuppimet = -1;
    dphipuppiUW = -1;
    dphipuppiUZ = -1;
    dphipuppiUA = -1;
    dphipfUW = -1;
    dphipfUZ = -1;
    dphipfUA = -1;
    dphipuppiU = -1;
    dphipfU = -1;
    trueGenBosonPt = -1;
    genBosonPt = -1;
    genBosonEta = -1;
    genBosonMass = -1;
    genBosonPhi = -1;
    genWPlusPt = -1;
    genWMinusPt = -1;
    genWPlusEta = -1;
    genWMinusEta = -1;
    genTopPt = -1;
    genTopIsHad = 0;
    genTopEta = -1;
    genAntiTopPt = -1;
    genAntiTopIsHad = 0;
    genAntiTopEta = -1;
    genTTPt = -1;
    genTTEta = -1;
    nJet = 0;
    nIsoJet = 0;
    jet1Flav = 0;
    jet1Phi = -1;
    jet1Pt = -1;
    jet1GenPt = -1;
    jet1Eta = -1;
    jet1CSV = -1;
    jet1IsTight = 0;
    jet2Flav = 0;
    jet2Phi = -1;
    jet2Pt = -1;
    jet2GenPt = -1;
    jet2Eta = -1;
    jet2CSV = -1;
    isojet1Pt = -1;
    isojet1CSV = -1;
    isojet1Flav = 0;
    isojet2Pt = -1;
    isojet2CSV = -1;
    isojet2Flav = 0;
    jot12Mass = -1;
    jot12DEta = -1;
    jetNBtags = 0;
    isojetNBtags = 0;
    nFatjet = 0;
    fj1Tau32 = -1;
    fj1Tau21 = -1;
    fj1Tau32SD = -1;
    fj1Tau21SD = -1;
    fj1MSD = -1;
    fj1MSDScaleUp = -1;
    fj1MSDScaleDown = -1;
    fj1MSDSmeared = -1;
    fj1MSDSmearedUp = -1;
    fj1MSDSmearedDown = -1;
    fj1MSD_corr = -1;
    fj1Pt = -1;
    fj1PtScaleUp = -1;
    fj1PtScaleDown = -1;
    fj1PtSmeared = -1;
    fj1PtSmearedUp = -1;
    fj1PtSmearedDown = -1;
    fj1Phi = -1;
    fj1Eta = -1;
    fj1M = -1;
    fj1MaxCSV = -1;
    fj1MinCSV = -1;
    fj1DoubleCSV = -1;
    fj1Nbs = 0;
    fj1gbb = 0;
    fj1GenPt = -1;
    fj1GenSize = -1;
    fj1IsMatched = 0;
    fj1GenWPt = -1;
    fj1GenWSize = -1;
    fj1IsWMatched = 0;
    fj1HighestPtGen = 0;
    fj1HighestPtGenPt = -1;
    fj1IsTight = 0;
    fj1IsLoose = 0;
    fj1RawPt = -1;
    fj1NHF = 0;
    fj1HTTMass = -1;
    fj1HTTFRec = -1;
    fj1IsClean = 0;
    fj1NConst = 0;
    fj1NSDConst = 0;
    fj1EFrac100 = -1;
    fj1SDEFrac100 = -1;
    nHF = 0;
    nLoosePhoton = 0;
    nTightPhoton = 0;
    loosePho1IsTight = 0;
    loosePho1Pt = -1;
    loosePho1Eta = -1;
    loosePho1Phi = -1;
    nLooseLep = 0;
    nLooseElectron = 0;
    nLooseMuon = 0;
    nTightLep = 0;
    nTightElectron = 0;
    nTightMuon = 0;
    looseLep1PdgId = 0;
    looseLep2PdgId = 0;
    looseLep1IsTight = 0;
    looseLep2IsTight = 0;
    looseLep1Pt = -1;
    looseLep1Eta = -1;
    looseLep1Phi = -1;
    looseLep2Pt = -1;
    looseLep2Eta = -1;
    looseLep2Phi = -1;
    diLepMass = -1;
    nTau = 0;
    mT = -1;
    hbbpt = -1;
    hbbeta = -1;
    hbbphi = -1;
    hbbm = -1;
    scaleUp = -1;
    scaleDown = -1;
    pdfUp = -1;
    pdfDown = -1;
}

void GeneralTree::WriteTree(TTree *t) {
  treePtr = t;
//STARTCUSTOMWRITE
  for (auto iter=signal_weights.begin(); iter!=signal_weights.end(); ++iter) {
    Book("rw_"+iter->first,&(signal_weights[iter->first]),"rw_"+iter->first+"/F");
  }

  Book("nJet",&nJet,"nJet/I");
  Book("nJot",&nJot,"nJot/I");
  if (monohiggs) {
    Book("jetPt",jetPt,"jetPt[nJot]/F");
    Book("jetEta",jetEta,"jetEta[nJot]/F");
    Book("jetPhi",jetPhi,"jetPhi[nJot]/F");
    Book("jetE",jetE,"jetE[nJot]/F");
    Book("jetCSV",jetCSV,"jetCSV[nJot]/F");
    Book("jetIso",jetIso,"jetIso[nJot]/F");
    Book("jetQGL",jetQGL,"jetQGL[nJot]/F");
    Book("jetLeadingLepPt",jetLeadingLepPt,"jetLeadingLepPt[nJot]/F");
    Book("jetLeadingTrkPt",jetLeadingTrkPt,"jetLeadingTrkPt[nJot]/F");
    Book("jetEMFrac",jetEMFrac,"jetEMFrac[nJot]/F");
    Book("jetHadFrac",jetHadFrac,"jetHadFrac[nJot]/F");
    Book("jetNLep",jetNLep,"jetNLep[nJot]/I");
    Book("jetGenPt",jetGenPt,"jetGenPt[nJot]/F");
    Book("jetGenFlavor",jetGenFlavor,"jetGenFlavor[nJot]/I");
    Book("fj1sjPt",fj1sjPt,"fj1sjPt[2]/F");
    Book("fj1sjPhi",fj1sjPhi,"fj1sjPhi[2]/F");
    Book("fj1sjEta",fj1sjEta,"fj1sjEta[2]/F");
    Book("fj1sjM",fj1sjM,"fj1sjM[2]/F");
    Book("fj1sjCSV",fj1sjCSV,"fj1sjCSV[2]/F");
    Book("fj1sjQGL",fj1sjQGL,"fj1sjQGL[2]/F");
    Book("fj1Nbs",&fj1Nbs,"fj1Nbs/I");
    Book("fj1gbb",&fj1gbb,"fj1gbb/I");
    Book("hbbpt",&hbbpt,"hbbpt/F");
    Book("hbbeta",&hbbeta,"hbbeta/F");
    Book("hbbphi",&hbbphi,"hbbphi/F");
    Book("hbbm",&hbbm,"hbbm/F");
    Book("hbbjtidx",hbbjtidx,"hbbjtidx[2]/I");
  }

  if (vbf) { 
    Book("jot1Phi",&jot1Phi,"jot1Phi/F");
    Book("jot1Pt",&jot1Pt,"jot1Pt/F");
    Book("jot1GenPt",&jot1GenPt,"jot1GenPt/F");
    Book("jot1Eta",&jot1Eta,"jot1Eta/F");
    Book("jot2Phi",&jot2Phi,"jot2Phi/F");
    Book("jot2Pt",&jot2Pt,"jot2Pt/F");
    Book("jot2GenPt",&jot2GenPt,"jot2GenPt/F");
    Book("jot2Eta",&jot2Eta,"jot2Eta/F");
    Book("jot12DPhi",&jot12DPhi,"jot12DPhi/F");
    Book("jot12Mass",&jot12Mass,"jot12Mass/F");
    Book("jot12DEta",&jot12DEta,"jot12DEta/F");
    Book("pfmetUp",&pfmetUp,"pfmetUp/F");
    Book("pfmetDown",&pfmetDown,"pfmetDown/F");
    Book("pfUWmagUp",&pfUWmagUp,"pfUWmagUp/F");
    Book("pfUZmagUp",&pfUZmagUp,"pfUZmagUp/F");
    Book("pfUAmagUp",&pfUAmagUp,"pfUAmagUp/F");
    Book("pfUmagUp",&pfUmagUp,"pfUmagUp/F");
    Book("pfUWmagDown",&pfUWmagDown,"pfUWmagDown/F");
    Book("pfUZmagDown",&pfUZmagDown,"pfUZmagDown/F");
    Book("pfUAmagDown",&pfUAmagDown,"pfUAmagDown/F");
    Book("pfUmagDown",&pfUmagDown,"pfUmagDown/F");
    Book("jot1EtaUp",&jot1EtaUp,"jot1EtaUp/F");
    Book("jot1EtaDown",&jot1EtaDown,"jot1EtaDown/F");
    Book("jot1PtUp",&jot1PtUp,"jot1PtUp/F");
    Book("jot1PtDown",&jot1PtDown,"jot1PtDown/F");
    Book("jot2PtUp",&jot2PtUp,"jot2PtUp/F");
    Book("jot2PtDown",&jot2PtDown,"jot2PtDown/F");
    Book("jot12MassUp",&jot12MassUp,"jot12MassUp/F");
    Book("jot12DEtaUp",&jot12DEtaUp,"jot12DEtaUp/F");
    Book("jot12DPhiUp",&jot12DPhiUp,"jot12DPhiUp/F");
    Book("jot12MassDown",&jot12MassDown,"jot12MassDown/F");
    Book("jot12DEtaDown",&jot12DEtaDown,"jot12DEtaDown/F");
    Book("jot12DPhiDown",&jot12DPhiDown,"jot12DPhiDown/F");
    Book("jot2EtaUp",&jot2EtaUp,"jot2EtaUp/F");
    Book("jot2EtaDown",&jot2EtaDown,"jot2EtaDown/F");
    Book("jot1VBFID",&jot1VBFID,"jot1VBFID/I");
    Book("sf_qcdV_VBF2lTight",&sf_qcdV_VBF2lTight,"sf_qcdV_VBF2lTight/F");
    Book("sf_qcdV_VBF2l",&sf_qcdV_VBF2l,"sf_qcdV_VBF2l/F");
    Book("barrelHTMiss",&barrelHTMiss,"barrelHTMiss/F");
    Book("barrelJet12Pt",&barrelJet12Pt,"barrelJet12Pt/F");
    Book("barrelJet1Pt",&barrelJet1Pt,"barrelJet1Pt/F");
    Book("barrelJet1Eta",&barrelJet1Eta,"barrelJet1Eta/F");
    Book("barrelHT",&barrelHT,"barrelHT/F");
    Book("sf_puUp",&sf_puUp,"sf_puUp/F");
    Book("sf_puDown",&sf_puDown,"sf_puDown/F");
    Book("genMuonPt",&genMuonPt,"genMuonPt/F");
    Book("genMuonEta",&genMuonEta,"genMuonEta/F");
    Book("genElectronPt",&genElectronPt,"genElectronPt/F");
    Book("genElectronEta",&genElectronEta,"genElectronEta/F");
    Book("genTauPt",&genTauPt,"genTauPt/F");
    Book("genTauEta",&genTauEta,"genTauEta/F");
    Book("sf_qcdV_VBFTight",&sf_qcdV_VBFTight,"sf_qcdV_VBFTight/F");
    Book("sf_metTrigVBF",&sf_metTrigVBF,"sf_metTrigVBF/F");
    Book("sf_metTrigZmmVBF",&sf_metTrigZmmVBF,"sf_metTrigZmmVBF/F");
    Book("sumETRaw",&sumETRaw,"sumETRaw/F");
    Book("sf_metTrigZmm",&sf_metTrigZmm,"sf_metTrigZmm/F");
    Book("sf_qcdV_VBF",&sf_qcdV_VBF,"sf_qcdV_VBF/F");
  }
  Book("scale",scale,"scale[6]/F");

  for (auto p : ecfParams) { 
    TString ecfn(makeECFString(p));
    Book("fj1"+ecfn,&(fj1ECFNs[p]),"fj1"+ecfn+"/F");
  }

  for (auto p : btagParams) {
    TString btagn(makeBTagSFString(p));
    Book(btagn,&(sf_btags[p]),btagn+"/F");
  }
  if(leptonic) {
    Book("looseLep1D0",&looseLep1D0,"looseLep1D0/F");
    Book("looseLep1Dz",&looseLep1Dz,"looseLep1Dz/F");
    Book("looseLep2D0",&looseLep2D0,"looseLep2D0/F");
    Book("looseLep2Dz",&looseLep2Dz,"looseLep2Dz/F");
    Book("looseLep3D0",&looseLep3D0,"looseLep3D0/F");
    Book("looseLep3Dz",&looseLep3Dz,"looseLep3Dz/F");
    Book("looseLep4D0",&looseLep4D0,"looseLep4D0/F");
    Book("looseLep4Dz",&looseLep4Dz,"looseLep4Dz/F");
    Book("looseLep1ChIsoPh",&looseLep1ChIsoPh,"looseLep1ChIsoPh/F");
    Book("looseLep1NhIsoPh",&looseLep1NhIsoPh,"looseLep1NhIsoPh/F");
    Book("looseLep1PhIsoPh",&looseLep1PhIsoPh,"looseLep1PhIsoPh/F");
    Book("looseLep1EcalIso",&looseLep1EcalIso,"looseLep1EcalIso/F");
    Book("looseLep1HcalIso",&looseLep1HcalIso,"looseLep1HcalIso/F");
    Book("looseLep1TrackIso",&looseLep1TrackIso,"looseLep1TrackIso/F");
    Book("looseLep1IsoPUOffset",&looseLep1IsoPUOffset,"looseLep1IsoPUOffset/F");
    Book("looseLep1Sieie",&looseLep1Sieie,"looseLep1Sieie/F");
    Book("looseLep1Sipip",&looseLep1Sipip,"looseLep1Sipip/F");
    Book("looseLep1DEtaInSeed",&looseLep1DEtaInSeed,"looseLep1DEtaInSeed/F");
    Book("looseLep1DPhiIn",&looseLep1DPhiIn,"looseLep1DPhiIn/F");
    Book("looseLep1Eseed",&looseLep1Eseed,"looseLep1Eseed/F");
    Book("looseLep1HOverE",&looseLep1HOverE,"looseLep1HOverE/F");
    Book("looseLep1EcalE",&looseLep1EcalE,"looseLep1EcalE/F");
    Book("looseLep1TrackP",&looseLep1TrackP,"looseLep1TrackP/F");
    Book("looseLep1NMissingHits",&looseLep1NMissingHits,"looseLep1NMissingHits/I");
    Book("looseLep1TripleCharge",&looseLep1TripleCharge,"looseLep1TripleCharge/I");
    Book("looseLep2ChIsoPh",&looseLep2ChIsoPh,"looseLep2ChIsoPh/F");
    Book("looseLep2NhIsoPh",&looseLep2NhIsoPh,"looseLep2NhIsoPh/F");
    Book("looseLep2PhIsoPh",&looseLep2PhIsoPh,"looseLep2PhIsoPh/F");
    Book("looseLep2EcalIso",&looseLep2EcalIso,"looseLep2EcalIso/F");
    Book("looseLep2HcalIso",&looseLep2HcalIso,"looseLep2HcalIso/F");
    Book("looseLep2TrackIso",&looseLep2TrackIso,"looseLep2TrackIso/F");
    Book("looseLep2IsoPUOffset",&looseLep2IsoPUOffset,"looseLep2IsoPUOffset/F");
    Book("looseLep2Sieie",&looseLep2Sieie,"looseLep2Sieie/F");
    Book("looseLep2Sipip",&looseLep2Sipip,"looseLep2Sipip/F");
    Book("looseLep2DEtaInSeed",&looseLep2DEtaInSeed,"looseLep2DEtaInSeed/F");
    Book("looseLep2DPhiIn",&looseLep2DPhiIn,"looseLep2DPhiIn/F");
    Book("looseLep2Eseed",&looseLep2Eseed,"looseLep2Eseed/F");
    Book("looseLep2HOverE",&looseLep2HOverE,"looseLep2HOverE/F");
    Book("looseLep2EcalE",&looseLep2EcalE,"looseLep2EcalE/F");
    Book("looseLep2TrackP",&looseLep2TrackP,"looseLep2TrackP/F");
    Book("looseLep2NMissingHits",&looseLep2NMissingHits,"looseLep2NMissingHits/I");
    Book("looseLep2TripleCharge",&looseLep2TripleCharge,"looseLep2TripleCharge/I");
    Book("looseLep3ChIsoPh",&looseLep3ChIsoPh,"looseLep3ChIsoPh/F");
    Book("looseLep3NhIsoPh",&looseLep3NhIsoPh,"looseLep3NhIsoPh/F");
    Book("looseLep3PhIsoPh",&looseLep3PhIsoPh,"looseLep3PhIsoPh/F");
    Book("looseLep3EcalIso",&looseLep3EcalIso,"looseLep3EcalIso/F");
    Book("looseLep3HcalIso",&looseLep3HcalIso,"looseLep3HcalIso/F");
    Book("looseLep3TrackIso",&looseLep3TrackIso,"looseLep3TrackIso/F");
    Book("looseLep3IsoPUOffset",&looseLep3IsoPUOffset,"looseLep3IsoPUOffset/F");
    Book("looseLep3Sieie",&looseLep3Sieie,"looseLep3Sieie/F");
    Book("looseLep3Sipip",&looseLep3Sipip,"looseLep3Sipip/F");
    Book("looseLep3DEtaInSeed",&looseLep3DEtaInSeed,"looseLep3DEtaInSeed/F");
    Book("looseLep3DPhiIn",&looseLep3DPhiIn,"looseLep3DPhiIn/F");
    Book("looseLep3Eseed",&looseLep3Eseed,"looseLep3Eseed/F");
    Book("looseLep3HOverE",&looseLep3HOverE,"looseLep3HOverE/F");
    Book("looseLep3EcalE",&looseLep3EcalE,"looseLep3EcalE/F");
    Book("looseLep3TrackP",&looseLep3TrackP,"looseLep3TrackP/F");
    Book("looseLep3NMissingHits",&looseLep3NMissingHits,"looseLep3NMissingHits/I");
    Book("looseLep3TripleCharge",&looseLep3TripleCharge,"looseLep3TripleCharge/I");
    Book("looseLep4ChIsoPh",&looseLep4ChIsoPh,"looseLep4ChIsoPh/F");
    Book("looseLep4NhIsoPh",&looseLep4NhIsoPh,"looseLep4NhIsoPh/F");
    Book("looseLep4PhIsoPh",&looseLep4PhIsoPh,"looseLep4PhIsoPh/F");
    Book("looseLep4EcalIso",&looseLep4EcalIso,"looseLep4EcalIso/F");
    Book("looseLep4HcalIso",&looseLep4HcalIso,"looseLep4HcalIso/F");
    Book("looseLep4TrackIso",&looseLep4TrackIso,"looseLep4TrackIso/F");
    Book("looseLep4IsoPUOffset",&looseLep4IsoPUOffset,"looseLep4IsoPUOffset/F");
    Book("looseLep4Sieie",&looseLep4Sieie,"looseLep4Sieie/F");
    Book("looseLep4Sipip",&looseLep4Sipip,"looseLep4Sipip/F");
    Book("looseLep4DEtaInSeed",&looseLep4DEtaInSeed,"looseLep4DEtaInSeed/F");
    Book("looseLep4DPhiIn",&looseLep4DPhiIn,"looseLep4DPhiIn/F");
    Book("looseLep4Eseed",&looseLep4Eseed,"looseLep4Eseed/F");
    Book("looseLep4HOverE",&looseLep4HOverE,"looseLep4HOverE/F");
    Book("looseLep4EcalE",&looseLep4EcalE,"looseLep4EcalE/F");
    Book("looseLep4TrackP",&looseLep4TrackP,"looseLep4TrackP/F");
    Book("looseLep4NMissingHits",&looseLep4NMissingHits,"looseLep4NMissingHits/I");
    Book("looseLep4TripleCharge",&looseLep4TripleCharge,"looseLep4TripleCharge/I");
    Book("looseLep1SelBit",&looseLep1SelBit,"looseLep1SelBit/I");
    Book("looseLep2SelBit",&looseLep2SelBit,"looseLep2SelBit/I");
    Book("looseLep3SelBit",&looseLep3SelBit,"looseLep3SelBit/I");
    Book("looseLep4SelBit",&looseLep4SelBit,"looseLep4SelBit/I");
    Book("looseLep3PdgId",&looseLep3PdgId,"looseLep3PdgId/I");
    Book("looseLep3IsTight",&looseLep3IsTight,"looseLep3IsTight/I");
    Book("looseLep3IsHLTSafe",&looseLep3IsHLTSafe,"looseLep3IsHLTSafe/I");
    Book("looseLep3Pt",&looseLep3Pt,"looseLep3Pt/F");
    Book("looseLep3Eta",&looseLep3Eta,"looseLep3Eta/F");
    Book("looseLep3Phi",&looseLep3Phi,"looseLep3Phi/F");
    Book("looseLep4PdgId",&looseLep4PdgId,"looseLep4PdgId/I");
    Book("looseLep4Pt",&looseLep4Pt,"looseLep4Pt/F");
    Book("looseLep4Eta",&looseLep4Eta,"looseLep4Eta/F");
    Book("looseLep4Phi",&looseLep4Phi,"looseLep4Phi/F");
    Book("looseLep4IsTight",&looseLep4IsTight,"looseLep4IsTight/I");
    Book("looseLep4IsHLTSafe",&looseLep4IsHLTSafe,"looseLep4IsHLTSafe/I");
    Book("sf_trk1",&sf_trk1,"sf_trk1/F");
    Book("sf_loose1",&sf_loose1,"sf_loose1/F");
    Book("sf_medium1",&sf_medium1,"sf_medium1/F");
    Book("sf_tight1",&sf_tight1,"sf_tight1/F");
    Book("sf_unc1",&sf_unc1,"sf_unc1/F");
    Book("sf_trk2",&sf_trk2,"sf_trk2/F");
    Book("sf_loose2",&sf_loose2,"sf_loose2/F");
    Book("sf_medium2",&sf_medium2,"sf_medium2/F");
    Book("sf_tight2",&sf_tight2,"sf_tight2/F");
    Book("sf_unc2",&sf_unc2,"sf_unc2/F");
    Book("sf_trk3",&sf_trk3,"sf_trk3/F");
    Book("sf_loose3",&sf_loose3,"sf_loose3/F");
    Book("sf_medium3",&sf_medium3,"sf_medium3/F");
    Book("sf_tight3",&sf_tight3,"sf_tight3/F");
    Book("sf_unc3",&sf_unc3,"sf_unc3/F");
    Book("sf_trk4",&sf_trk4,"sf_trk4/F");
    Book("sf_loose4",&sf_loose4,"sf_loose4/F");
    Book("sf_medium4",&sf_medium4,"sf_medium4/F");
    Book("sf_tight4",&sf_tight4,"sf_tight4/F");
    Book("sf_unc4",&sf_unc4,"sf_unc4/F");
    Book("looseLep1IsSoftMuon",&looseLep1IsSoftMuon,"looseLep1IsSoftMuon/I");
    Book("looseLep1IsGlobalMuon",&looseLep1IsGlobalMuon,"looseLep1IsGlobalMuon/I");
    Book("looseLep1IsTrackerMuon",&looseLep1IsTrackerMuon,"looseLep1IsTrackerMuon/I");
    Book("looseLep1NValidMuon",&looseLep1NValidMuon,"looseLep1NValidMuon/I");
    Book("looseLep1NValidPixel",&looseLep1NValidPixel,"looseLep1NValidPixel/I");
    Book("looseLep1TrkLayersWithMmt",&looseLep1TrkLayersWithMmt,"looseLep1TrkLayersWithMmt/I");
    Book("looseLep1PixLayersWithMmt",&looseLep1PixLayersWithMmt,"looseLep1PixLayersWithMmt/I");
    Book("looseLep1NMatched",&looseLep1NMatched,"looseLep1NMatched/I");
    Book("looseLep1Chi2LocalPosition",&looseLep1Chi2LocalPosition,"looseLep1Chi2LocalPosition/I");
    Book("looseLep1TrkKink",&looseLep1TrkKink,"looseLep1TrkKink/I");
    Book("looseLep1ValidFraction",&looseLep1ValidFraction,"looseLep1ValidFraction/F");
    Book("looseLep1NormChi2",&looseLep1NormChi2,"looseLep1NormChi2/F");
    Book("looseLep1SegmentCompatibility",&looseLep1SegmentCompatibility,"looseLep1SegmentCompatibility/F");
    Book("looseLep2IsSoftMuon",&looseLep2IsSoftMuon,"looseLep2IsSoftMuon/I");
    Book("looseLep2IsGlobalMuon",&looseLep2IsGlobalMuon,"looseLep2IsGlobalMuon/I");
    Book("looseLep2IsTrackerMuon",&looseLep2IsTrackerMuon,"looseLep2IsTrackerMuon/I");
    Book("looseLep2NValidMuon",&looseLep2NValidMuon,"looseLep2NValidMuon/I");
    Book("looseLep2NValidPixel",&looseLep2NValidPixel,"looseLep2NValidPixel/I");
    Book("looseLep2TrkLayersWithMmt",&looseLep2TrkLayersWithMmt,"looseLep2TrkLayersWithMmt/I");
    Book("looseLep2PixLayersWithMmt",&looseLep2PixLayersWithMmt,"looseLep2PixLayersWithMmt/I");
    Book("looseLep2NMatched",&looseLep2NMatched,"looseLep2NMatched/I");
    Book("looseLep2Chi2LocalPosition",&looseLep2Chi2LocalPosition,"looseLep2Chi2LocalPosition/I");
    Book("looseLep2TrkKink",&looseLep2TrkKink,"looseLep2TrkKink/I");
    Book("looseLep2ValidFraction",&looseLep2ValidFraction,"looseLep2ValidFraction/F");
    Book("looseLep2NormChi2",&looseLep2NormChi2,"looseLep2NormChi2/F");
    Book("looseLep2SegmentCompatibility",&looseLep2SegmentCompatibility,"looseLep2SegmentCompatibility/F");
    Book("looseLep3IsSoftMuon",&looseLep3IsSoftMuon,"looseLep3IsSoftMuon/I");
    Book("looseLep3IsGlobalMuon",&looseLep3IsGlobalMuon,"looseLep3IsGlobalMuon/I");
    Book("looseLep3IsTrackerMuon",&looseLep3IsTrackerMuon,"looseLep3IsTrackerMuon/I");
    Book("looseLep3NValidMuon",&looseLep3NValidMuon,"looseLep3NValidMuon/I");
    Book("looseLep3NValidPixel",&looseLep3NValidPixel,"looseLep3NValidPixel/I");
    Book("looseLep3TrkLayersWithMmt",&looseLep3TrkLayersWithMmt,"looseLep3TrkLayersWithMmt/I");
    Book("looseLep3PixLayersWithMmt",&looseLep3PixLayersWithMmt,"looseLep3PixLayersWithMmt/I");
    Book("looseLep3NMatched",&looseLep3NMatched,"looseLep3NMatched/I");
    Book("looseLep3Chi2LocalPosition",&looseLep3Chi2LocalPosition,"looseLep3Chi2LocalPosition/I");
    Book("looseLep3TrkKink",&looseLep3TrkKink,"looseLep3TrkKink/I");
    Book("looseLep3ValidFraction",&looseLep3ValidFraction,"looseLep3ValidFraction/F");
    Book("looseLep3NormChi2",&looseLep3NormChi2,"looseLep3NormChi2/F");
    Book("looseLep3SegmentCompatibility",&looseLep3SegmentCompatibility,"looseLep3SegmentCompatibility/F");
    Book("looseLep4IsSoftMuon",&looseLep4IsSoftMuon,"looseLep4IsSoftMuon/I");
    Book("looseLep4IsGlobalMuon",&looseLep4IsGlobalMuon,"looseLep4IsGlobalMuon/I");
    Book("looseLep4IsTrackerMuon",&looseLep4IsTrackerMuon,"looseLep4IsTrackerMuon/I");
    Book("looseLep4NValidMuon",&looseLep4NValidMuon,"looseLep4NValidMuon/I");
    Book("looseLep4NValidPixel",&looseLep4NValidPixel,"looseLep4NValidPixel/I");
    Book("looseLep4TrkLayersWithMmt",&looseLep4TrkLayersWithMmt,"looseLep4TrkLayersWithMmt/I");
    Book("looseLep4PixLayersWithMmt",&looseLep4PixLayersWithMmt,"looseLep4PixLayersWithMmt/I");
    Book("looseLep4NMatched",&looseLep4NMatched,"looseLep4NMatched/I");
    Book("looseLep4Chi2LocalPosition",&looseLep4Chi2LocalPosition,"looseLep4Chi2LocalPosition/I");
    Book("looseLep4TrkKink",&looseLep4TrkKink,"looseLep4TrkKink/I");
    Book("looseLep4ValidFraction",&looseLep4ValidFraction,"looseLep4ValidFraction/F");
    Book("looseLep4NormChi2",&looseLep4NormChi2,"looseLep4NormChi2/F");
    Book("looseLep4SegmentCompatibility",&looseLep4SegmentCompatibility,"looseLep4SegmentCompatibility/F");
  }
//ENDCUSTOMWRITE
    Book("whichRecoil",&whichRecoil,"whichRecoil/I");
    Book("genJet1Pt",&genJet1Pt,"genJet1Pt/F");
    Book("genJet2Pt",&genJet2Pt,"genJet2Pt/F");
    Book("genJet1Eta",&genJet1Eta,"genJet1Eta/F");
    Book("genJet2Eta",&genJet2Eta,"genJet2Eta/F");
    Book("genMjj",&genMjj,"genMjj/F");
    Book("badECALFilter",&badECALFilter,"badECALFilter/I");
    Book("jetNMBtags",&jetNMBtags,"jetNMBtags/I");
    Book("pfmetRaw",&pfmetRaw,"pfmetRaw/F");
    Book("nAK8jet",&nAK8jet,"nAK8jet/I");
    Book("ak81Pt",&ak81Pt,"ak81Pt/F");
    Book("ak81Eta",&ak81Eta,"ak81Eta/F");
    Book("ak81Phi",&ak81Phi,"ak81Phi/F");
    Book("ak81MaxCSV",&ak81MaxCSV,"ak81MaxCSV/F");
    Book("nB",&nB,"nB/I");
    Book("fj1MSDScaleUp_sj",&fj1MSDScaleUp_sj,"fj1MSDScaleUp_sj/F");
    Book("fj1MSDScaleDown_sj",&fj1MSDScaleDown_sj,"fj1MSDScaleDown_sj/F");
    Book("fj1MSDSmeared_sj",&fj1MSDSmeared_sj,"fj1MSDSmeared_sj/F");
    Book("fj1MSDSmearedUp_sj",&fj1MSDSmearedUp_sj,"fj1MSDSmearedUp_sj/F");
    Book("fj1MSDSmearedDown_sj",&fj1MSDSmearedDown_sj,"fj1MSDSmearedDown_sj/F");
    Book("fj1PtScaleUp_sj",&fj1PtScaleUp_sj,"fj1PtScaleUp_sj/F");
    Book("fj1PtScaleDown_sj",&fj1PtScaleDown_sj,"fj1PtScaleDown_sj/F");
    Book("fj1PtSmeared_sj",&fj1PtSmeared_sj,"fj1PtSmeared_sj/F");
    Book("fj1PtSmearedUp_sj",&fj1PtSmearedUp_sj,"fj1PtSmearedUp_sj/F");
    Book("fj1PtSmearedDown_sj",&fj1PtSmearedDown_sj,"fj1PtSmearedDown_sj/F");
    Book("isGS",&isGS,"isGS/I");
    Book("fj1SubMaxCSV",&fj1SubMaxCSV,"fj1SubMaxCSV/F");
    Book("looseLep1IsHLTSafe",&looseLep1IsHLTSafe,"looseLep1IsHLTSafe/I");
    Book("looseLep2IsHLTSafe",&looseLep2IsHLTSafe,"looseLep2IsHLTSafe/I");
    Book("runNumber",&runNumber,"runNumber/I");
    Book("lumiNumber",&lumiNumber,"lumiNumber/I");
    Book("eventNumber",&eventNumber,"eventNumber/l");
    Book("npv",&npv,"npv/I");
    Book("pu",&pu,"pu/I");
    Book("mcWeight",&mcWeight,"mcWeight/F");
    Book("trigger",&trigger,"trigger/I");
    Book("metFilter",&metFilter,"metFilter/I");
    Book("egmFilter",&egmFilter,"egmFilter/I");
    Book("filter_maxRecoil",&filter_maxRecoil,"filter_maxRecoil/F");
    Book("filter_whichRecoil",&filter_whichRecoil,"filter_whichRecoil/F");
    Book("sf_ewkV",&sf_ewkV,"sf_ewkV/F");
    Book("sf_qcdV",&sf_qcdV,"sf_qcdV/F");
    Book("sf_ewkV2j",&sf_ewkV2j,"sf_ewkV2j/F");
    Book("sf_qcdV2j",&sf_qcdV2j,"sf_qcdV2j/F");
    Book("sf_qcdTT",&sf_qcdTT,"sf_qcdTT/F");
    Book("sf_lepID",&sf_lepID,"sf_lepID/F");
    Book("sf_lepIso",&sf_lepIso,"sf_lepIso/F");
    Book("sf_lepTrack",&sf_lepTrack,"sf_lepTrack/F");
    Book("sf_pho",&sf_pho,"sf_pho/F");
    Book("sf_eleTrig",&sf_eleTrig,"sf_eleTrig/F");
    Book("sf_phoTrig",&sf_phoTrig,"sf_phoTrig/F");
    Book("sf_metTrig",&sf_metTrig,"sf_metTrig/F");
    Book("sf_pu",&sf_pu,"sf_pu/F");
    Book("sf_npv",&sf_npv,"sf_npv/F");
    Book("sf_tt",&sf_tt,"sf_tt/F");
    Book("sf_tt_ext",&sf_tt_ext,"sf_tt_ext/F");
    Book("sf_tt_bound",&sf_tt_bound,"sf_tt_bound/F");
    Book("sf_tt8TeV",&sf_tt8TeV,"sf_tt8TeV/F");
    Book("sf_tt8TeV_ext",&sf_tt8TeV_ext,"sf_tt8TeV_ext/F");
    Book("sf_tt8TeV_bound",&sf_tt8TeV_bound,"sf_tt8TeV_bound/F");
    Book("sf_phoPurity",&sf_phoPurity,"sf_phoPurity/F");
    Book("pfmet",&pfmet,"pfmet/F");
    Book("pfmetphi",&pfmetphi,"pfmetphi/F");
    Book("pfmetnomu",&pfmetnomu,"pfmetnomu/F");
    Book("puppimet",&puppimet,"puppimet/F");
    Book("puppimetphi",&puppimetphi,"puppimetphi/F");
    Book("calomet",&calomet,"calomet/F");
    Book("calometphi",&calometphi,"calometphi/F");
    Book("pfcalobalance",&pfcalobalance,"pfcalobalance/F");
    Book("sumET",&sumET,"sumET/F");
    Book("trkmet",&trkmet,"trkmet/F");
    Book("puppiUWmag",&puppiUWmag,"puppiUWmag/F");
    Book("puppiUWphi",&puppiUWphi,"puppiUWphi/F");
    Book("puppiUZmag",&puppiUZmag,"puppiUZmag/F");
    Book("puppiUZphi",&puppiUZphi,"puppiUZphi/F");
    Book("puppiUAmag",&puppiUAmag,"puppiUAmag/F");
    Book("puppiUAphi",&puppiUAphi,"puppiUAphi/F");
    Book("puppiUperp",&puppiUperp,"puppiUperp/F");
    Book("puppiUpara",&puppiUpara,"puppiUpara/F");
    Book("puppiUmag",&puppiUmag,"puppiUmag/F");
    Book("puppiUphi",&puppiUphi,"puppiUphi/F");
    Book("pfUWmag",&pfUWmag,"pfUWmag/F");
    Book("pfUWphi",&pfUWphi,"pfUWphi/F");
    Book("pfUZmag",&pfUZmag,"pfUZmag/F");
    Book("pfUZphi",&pfUZphi,"pfUZphi/F");
    Book("pfUAmag",&pfUAmag,"pfUAmag/F");
    Book("pfUAphi",&pfUAphi,"pfUAphi/F");
    Book("pfUperp",&pfUperp,"pfUperp/F");
    Book("pfUpara",&pfUpara,"pfUpara/F");
    Book("pfUmag",&pfUmag,"pfUmag/F");
    Book("pfUphi",&pfUphi,"pfUphi/F");
    Book("dphipfmet",&dphipfmet,"dphipfmet/F");
    Book("dphipuppimet",&dphipuppimet,"dphipuppimet/F");
    Book("dphipuppiUW",&dphipuppiUW,"dphipuppiUW/F");
    Book("dphipuppiUZ",&dphipuppiUZ,"dphipuppiUZ/F");
    Book("dphipuppiUA",&dphipuppiUA,"dphipuppiUA/F");
    Book("dphipfUW",&dphipfUW,"dphipfUW/F");
    Book("dphipfUZ",&dphipfUZ,"dphipfUZ/F");
    Book("dphipfUA",&dphipfUA,"dphipfUA/F");
    Book("dphipuppiU",&dphipuppiU,"dphipuppiU/F");
    Book("dphipfU",&dphipfU,"dphipfU/F");
    Book("trueGenBosonPt",&trueGenBosonPt,"trueGenBosonPt/F");
    Book("genBosonPt",&genBosonPt,"genBosonPt/F");
    Book("genBosonEta",&genBosonEta,"genBosonEta/F");
    Book("genBosonMass",&genBosonMass,"genBosonMass/F");
    Book("genBosonPhi",&genBosonPhi,"genBosonPhi/F");
    Book("genWPlusPt",&genWPlusPt,"genWPlusPt/F");
    Book("genWMinusPt",&genWMinusPt,"genWMinusPt/F");
    Book("genWPlusEta",&genWPlusEta,"genWPlusEta/F");
    Book("genWMinusEta",&genWMinusEta,"genWMinusEta/F");
    Book("genTopPt",&genTopPt,"genTopPt/F");
    Book("genTopIsHad",&genTopIsHad,"genTopIsHad/I");
    Book("genTopEta",&genTopEta,"genTopEta/F");
    Book("genAntiTopPt",&genAntiTopPt,"genAntiTopPt/F");
    Book("genAntiTopIsHad",&genAntiTopIsHad,"genAntiTopIsHad/I");
    Book("genAntiTopEta",&genAntiTopEta,"genAntiTopEta/F");
    Book("genTTPt",&genTTPt,"genTTPt/F");
    Book("genTTEta",&genTTEta,"genTTEta/F");
    Book("nIsoJet",&nIsoJet,"nIsoJet/I");
    Book("jet1Flav",&jet1Flav,"jet1Flav/I");
    Book("jet1Phi",&jet1Phi,"jet1Phi/F");
    Book("jet1Pt",&jet1Pt,"jet1Pt/F");
    Book("jet1GenPt",&jet1GenPt,"jet1GenPt/F");
    Book("jet1Eta",&jet1Eta,"jet1Eta/F");
    Book("jet1CSV",&jet1CSV,"jet1CSV/F");
    Book("jet1IsTight",&jet1IsTight,"jet1IsTight/I");
    Book("jet2Flav",&jet2Flav,"jet2Flav/I");
    Book("jet2Phi",&jet2Phi,"jet2Phi/F");
    Book("jet2Pt",&jet2Pt,"jet2Pt/F");
    Book("jet2GenPt",&jet2GenPt,"jet2GenPt/F");
    Book("jet2Eta",&jet2Eta,"jet2Eta/F");
    Book("jet2CSV",&jet2CSV,"jet2CSV/F");
    Book("isojet1Pt",&isojet1Pt,"isojet1Pt/F");
    Book("isojet1CSV",&isojet1CSV,"isojet1CSV/F");
    Book("isojet1Flav",&isojet1Flav,"isojet1Flav/I");
    Book("isojet2Pt",&isojet2Pt,"isojet2Pt/F");
    Book("isojet2CSV",&isojet2CSV,"isojet2CSV/F");
    Book("isojet2Flav",&isojet2Flav,"isojet2Flav/I");
    Book("jetNBtags",&jetNBtags,"jetNBtags/I");
    Book("isojetNBtags",&isojetNBtags,"isojetNBtags/I");
    Book("nFatjet",&nFatjet,"nFatjet/I");
    Book("fj1Tau32",&fj1Tau32,"fj1Tau32/F");
    Book("fj1Tau21",&fj1Tau21,"fj1Tau21/F");
    Book("fj1Tau32SD",&fj1Tau32SD,"fj1Tau32SD/F");
    Book("fj1Tau21SD",&fj1Tau21SD,"fj1Tau21SD/F");
    Book("fj1MSD",&fj1MSD,"fj1MSD/F");
    Book("fj1MSDScaleUp",&fj1MSDScaleUp,"fj1MSDScaleUp/F");
    Book("fj1MSDScaleDown",&fj1MSDScaleDown,"fj1MSDScaleDown/F");
    Book("fj1MSDSmeared",&fj1MSDSmeared,"fj1MSDSmeared/F");
    Book("fj1MSDSmearedUp",&fj1MSDSmearedUp,"fj1MSDSmearedUp/F");
    Book("fj1MSDSmearedDown",&fj1MSDSmearedDown,"fj1MSDSmearedDown/F");
    Book("fj1MSD_corr",&fj1MSD_corr,"fj1MSD_corr/F");
    Book("fj1Pt",&fj1Pt,"fj1Pt/F");
    Book("fj1PtScaleUp",&fj1PtScaleUp,"fj1PtScaleUp/F");
    Book("fj1PtScaleDown",&fj1PtScaleDown,"fj1PtScaleDown/F");
    Book("fj1PtSmeared",&fj1PtSmeared,"fj1PtSmeared/F");
    Book("fj1PtSmearedUp",&fj1PtSmearedUp,"fj1PtSmearedUp/F");
    Book("fj1PtSmearedDown",&fj1PtSmearedDown,"fj1PtSmearedDown/F");
    Book("fj1Phi",&fj1Phi,"fj1Phi/F");
    Book("fj1Eta",&fj1Eta,"fj1Eta/F");
    Book("fj1M",&fj1M,"fj1M/F");
    Book("fj1MaxCSV",&fj1MaxCSV,"fj1MaxCSV/F");
    Book("fj1MinCSV",&fj1MinCSV,"fj1MinCSV/F");
    Book("fj1DoubleCSV",&fj1DoubleCSV,"fj1DoubleCSV/F");
    Book("fj1GenPt",&fj1GenPt,"fj1GenPt/F");
    Book("fj1GenSize",&fj1GenSize,"fj1GenSize/F");
    Book("fj1IsMatched",&fj1IsMatched,"fj1IsMatched/I");
    Book("fj1GenWPt",&fj1GenWPt,"fj1GenWPt/F");
    Book("fj1GenWSize",&fj1GenWSize,"fj1GenWSize/F");
    Book("fj1IsWMatched",&fj1IsWMatched,"fj1IsWMatched/I");
    Book("fj1HighestPtGen",&fj1HighestPtGen,"fj1HighestPtGen/I");
    Book("fj1HighestPtGenPt",&fj1HighestPtGenPt,"fj1HighestPtGenPt/F");
    Book("fj1IsTight",&fj1IsTight,"fj1IsTight/I");
    Book("fj1IsLoose",&fj1IsLoose,"fj1IsLoose/I");
    Book("fj1RawPt",&fj1RawPt,"fj1RawPt/F");
    Book("fj1NHF",&fj1NHF,"fj1NHF/I");
    Book("fj1HTTMass",&fj1HTTMass,"fj1HTTMass/F");
    Book("fj1HTTFRec",&fj1HTTFRec,"fj1HTTFRec/F");
    Book("fj1IsClean",&fj1IsClean,"fj1IsClean/I");
    Book("fj1NConst",&fj1NConst,"fj1NConst/I");
    Book("fj1NSDConst",&fj1NSDConst,"fj1NSDConst/I");
    Book("fj1EFrac100",&fj1EFrac100,"fj1EFrac100/F");
    Book("fj1SDEFrac100",&fj1SDEFrac100,"fj1SDEFrac100/F");
    Book("nHF",&nHF,"nHF/I");
    Book("nLoosePhoton",&nLoosePhoton,"nLoosePhoton/I");
    Book("nTightPhoton",&nTightPhoton,"nTightPhoton/I");
    Book("loosePho1IsTight",&loosePho1IsTight,"loosePho1IsTight/I");
    Book("loosePho1Pt",&loosePho1Pt,"loosePho1Pt/F");
    Book("loosePho1Eta",&loosePho1Eta,"loosePho1Eta/F");
    Book("loosePho1Phi",&loosePho1Phi,"loosePho1Phi/F");
    Book("nLooseLep",&nLooseLep,"nLooseLep/I");
    Book("nLooseElectron",&nLooseElectron,"nLooseElectron/I");
    Book("nLooseMuon",&nLooseMuon,"nLooseMuon/I");
    Book("nTightLep",&nTightLep,"nTightLep/I");
    Book("nTightElectron",&nTightElectron,"nTightElectron/I");
    Book("nTightMuon",&nTightMuon,"nTightMuon/I");
    Book("looseLep1PdgId",&looseLep1PdgId,"looseLep1PdgId/I");
    Book("looseLep2PdgId",&looseLep2PdgId,"looseLep2PdgId/I");
    Book("looseLep1IsTight",&looseLep1IsTight,"looseLep1IsTight/I");
    Book("looseLep2IsTight",&looseLep2IsTight,"looseLep2IsTight/I");
    Book("looseLep1Pt",&looseLep1Pt,"looseLep1Pt/F");
    Book("looseLep1Eta",&looseLep1Eta,"looseLep1Eta/F");
    Book("looseLep1Phi",&looseLep1Phi,"looseLep1Phi/F");
    Book("looseLep2Pt",&looseLep2Pt,"looseLep2Pt/F");
    Book("looseLep2Eta",&looseLep2Eta,"looseLep2Eta/F");
    Book("looseLep2Phi",&looseLep2Phi,"looseLep2Phi/F");
    Book("diLepMass",&diLepMass,"diLepMass/F");
    Book("nTau",&nTau,"nTau/I");
    Book("mT",&mT,"mT/F");
    Book("scaleUp",&scaleUp,"scaleUp/F");
    Book("scaleDown",&scaleDown,"scaleDown/F");
    Book("pdfUp",&pdfUp,"pdfUp/F");
    Book("pdfDown",&pdfDown,"pdfDown/F");
}

